# Generated by Django 3.1.3 on 2020-12-26 17:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_failure_recovered_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='api_key',
            field=models.CharField(default=str(uuid.uuid4()), max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='failure',
            name='reason',
            field=models.CharField(blank=True, choices=[('invalid_value', 'Invalid Value'), ('key_error', 'Key Error'), ('value_error', 'Value Error'), ('status_code', 'Status Code'), (
                'connection_error', 'Connection Error'), ('timeout_error', 'Timeout Error'), ('http_error', 'HTTP Error'), ('receive_alert', 'Receive Alert')], max_length=20, null=True),
        ),
    ]
